name: Playwright Tests for AI Marketing Web Builder

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web-builder/package-lock.json
    
    - name: Install dependencies
      working-directory: ./web-builder
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./web-builder
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      working-directory: ./web-builder
      run: npm run test:ci
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: web-builder/playwright-report/
        retention-days: 30

  magic-moment-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web-builder/package-lock.json
    
    - name: Install dependencies
      working-directory: ./web-builder
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./web-builder
      run: npx playwright install chromium
    
    - name: Start backend services
      working-directory: ./web-builder/backend
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        uvicorn src.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
    
    - name: Run Magic Moment E2E Test
      working-directory: ./web-builder
      run: npm run test:magic-moment
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: magic-moment-results
        path: web-builder/test-results/
        retention-days: 7

  performance-benchmark:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web-builder/package-lock.json
    
    - name: Install dependencies
      working-directory: ./web-builder
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./web-builder
      run: npx playwright install chromium
    
    - name: Run Performance Tests
      working-directory: ./web-builder
      run: npx playwright test tests/e2e/ai-customization.spec.ts --grep="performance"
    
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: web-builder/performance-results/
        retention-days: 30